title: Ati's trading experiment
logo: /assets/img/logo.png
description: Documenting my journey in investment 
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal

defaults:
  -
    scope:
      path: tickers
    values:
      identifier: ticker
      layout: ticker

