theme: jekyll-theme-hacker
title: trade with ati

defaults:
  # Journals
  - scope:
      path: "tikers"
      type: posts
    values:
      permalink: ticker/:category/
      category: journals
      foo: bar